// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQhvRLMHcMWq7ploESLNpm3gqXyi2y4ck',
    appId: '1:1013208214200:web:738cc5aced4f7e659aa24d',
    messagingSenderId: '1013208214200',
    projectId: 'alu-internship-app-5017f',
    authDomain: 'alu-internship-app-5017f.firebaseapp.com',
    storageBucket: 'alu-internship-app-5017f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBafGErwmLlTxTL-k533rELMrXjJVrVgCg',
    appId: '1:1013208214200:android:3d7ee2a7c741b67f9aa24d',
    messagingSenderId: '1013208214200',
    projectId: 'alu-internship-app-5017f',
    storageBucket: 'alu-internship-app-5017f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9mVnCuNP7SX0VtSEV33T0EDTQkPS-IS0',
    appId: '1:1013208214200:ios:6dd4285982adbd769aa24d',
    messagingSenderId: '1013208214200',
    projectId: 'alu-internship-app-5017f',
    storageBucket: 'alu-internship-app-5017f.firebasestorage.app',
    iosBundleId: 'com.example.aluInternshipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9mVnCuNP7SX0VtSEV33T0EDTQkPS-IS0',
    appId: '1:1013208214200:ios:6dd4285982adbd769aa24d',
    messagingSenderId: '1013208214200',
    projectId: 'alu-internship-app-5017f',
    storageBucket: 'alu-internship-app-5017f.firebasestorage.app',
    iosBundleId: 'com.example.aluInternshipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQhvRLMHcMWq7ploESLNpm3gqXyi2y4ck',
    appId: '1:1013208214200:web:6f13e8fd4000cae69aa24d',
    messagingSenderId: '1013208214200',
    projectId: 'alu-internship-app-5017f',
    authDomain: 'alu-internship-app-5017f.firebaseapp.com',
    storageBucket: 'alu-internship-app-5017f.firebasestorage.app',
  );
}
